// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace BaseGamePlayTags
{
	//Input Tags
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnEquip)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll)
    
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Hold)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Hold_Block)

	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggle)
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggle_Targeting)
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SwitchTarget)


    //Player Tags
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Roll)
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Block)
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Targeting)


    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Weapon_Equip)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Weapon_UnEquip)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause)
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SuccessBlock)
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Left)
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Right)

    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rolling)
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Blocking)
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Targeting)

    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy)

    //Enemy Tags
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_HitReact)
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_SummonEnemies)
	
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Strafing)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_UnderAttack)
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_UnBlockableAttack)
	
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_SummonEnemies)

    //Shared Tags
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit)
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact)
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_SpawnProjectile)
	
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage)
    
    PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead)
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Front)
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Left)
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Right)
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Back)
        
}
